<a href="https://colab.research.google.com/github/FerdyAgustiann/Ferdy/blob/main/Latihan_DAA__Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import datetime
tanggal_hari_ini = str(datetime.date.today())
aList = ["Ferdy Agustian","2022071018","Informatika","Desain dan Analisis Algoritma",tanggal_hari_ini,"Universitas Pembangunan Jaya"]
print(aList)

['Ferdy Agustian', '2022071018', 'Informatika', 'Desain dan Analisis Algoritma', '2023-09-13', 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[0]

'Red'

In [ ]:
print(aList[1])

2022071018


In [ ]:
print(aList[5])

Universitas Pembangunan Jaya


In [ ]:
print (bin_colors[1:3])

['Green', 'Blue']


In [ ]:
print (aList[1:3])

['2022071018', 'Informatika']


In [ ]:
for aColor in bin_colors:
 print(aColor + " Square ")


Red Square 
Green Square 
Blue Square 
Yellow Square 


In [ ]:
for dataMahasiswa in aList:
  print("UPJ" , dataMahasiswa)

UPJ Ferdy Agustian
UPJ 2022071018
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ 2023-09-13
UPJ Universitas Pembangunan Jaya


In [ ]:
for dataMahasiswa in aList:
  print(dataMahasiswa , "Square")

Ferdy Agustian Square
2022071018 Square
Informatika Square
Desain dan Analisis Algoritma Square
2023-09-13 Square
Universitas Pembangunan Jaya Square


In [ ]:
bin_colors[1]

'Green'

In [ ]:
bin_colors[2:]

['Blue', 'Yellow']

In [ ]:
bin_UPJ=['Universitas','Pembangunan','Jaya']
bin_UPJ

['Universitas', 'Pembangunan', 'Jaya']

In [73]:
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)
nested_tuple = (pertama, kedua, ketiga, keempat)

print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [66]:
latihan={
    "Nama":"Ferdy Agustian",
    "NIM":"2022071018",
    "Prodi":"Informatika",
    "Universitas":"UPJ"
}
print(latihan)

{'Nama': 'Ferdy Agustian', 'NIM': '2022071018', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [69]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)

print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [70]:
red = {"dandelions", "leaves", "fire hydrant"}
green = {"rose", "blood", "leaves", "fire hydrant"}

print(red|green)
print(red&green)

{'fire hydrant', 'rose', 'blood', 'leaves', 'dandelions'}
{'leaves', 'fire hydrant'}


In [71]:
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')

In [72]:
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
